# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'huyen-nguyen'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'Teaching', url: 'teaching/'}
- {name: 'Résumé', url: 'docs/HuyenNguyen-Resume.pdf'}
- {name: 'CV', url: 'docs/HuyenNguyen-CV.pdf'}
- {name: 'Blog', url: 'blog/'}
- {name: 'About',   url: 'about/'}
#- {name: 'Contact', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/huyen-nguyen'}
- {icon: 'twitter',    link: 'https://twitter.com/huyendoesstuff'}
- {icon: 'linkedin',   link: 'http://www.linkedin.com/in/huyen-n-nguyen/'}
- {icon: 'google-scholar',   link: 'https://scholar.google.com/citations?user=tsrO-ZgAAAAJ&hl=en', academic: true}

#- {icon: 'envelope',   link: 'mailto:huyen24nguyen@gmail.com'}
#- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

#sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
